Message.create(content: 'Hello World')
Message.create(content: 'Bonjour à tous')
Message.create(content: 'Buona Serata')
Message.create(content: 'Buenas Noches')
Message.create(content: 'Welcome to Rails')
